export const TOGGLE_IS_CHECK = 'toggleIscheck'
export const COUNT_DECREMENT = 'countDecrement'
export const COUNT_INCREMENT = 'countIncrement'
export const TOGGLE_ALL_IS_CHECK = 'toggleAllIscheck'
export const TOGGLE_IS_EDIT = 'toggleIsEdit'
export const DELE_ITEM = 'deleItem'
export const ON_ADD_CART = 'onAddCart'
